# Generated by Django 3.0.3 on 2020-12-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0002_auto_20201221_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='step_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
            ],
        ),
    ]
