# Generated by Django 3.0.3 on 2020-12-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0004_step_tracker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_tracker',
            name='name',
        ),
    ]
