# Generated by Django 3.0.3 on 2021-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0008_notebookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookmodel',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='notebookmodel',
            name='functions',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
