# Generated by Django 3.0.3 on 2021-01-12 19:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0010_auto_20210112_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=jsonfield.fields.JSONField(default=dict, unique=True),
        ),
    ]
