# Generated by Django 3.0.3 on 2021-01-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0011_auto_20210112_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookmodel',
            name='notebook_group',
            field=models.CharField(default='Test_Group', max_length=50),
        ),
        migrations.AlterField(
            model_name='notebookmodel',
            name='notebook',
            field=models.FileField(upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
