# Generated by Django 3.0.3 on 2021-01-12 19:36

from django.db import migrations, models
import importJupyter.models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0012_auto_20210112_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookmodel',
            name='notebook',
            field=models.FileField(upload_to=importJupyter.models.generate_filename),
        ),
    ]
