# Generated by Django 3.0.3 on 2021-01-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0013_auto_20210112_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookmodel',
            name='notebook_test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
