# Generated by Django 3.0.3 on 2021-01-14 21:13

from django.db import migrations, models
import importJupyter.models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0014_notebookmodel_notebook_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookmodel',
            name='notebook_test',
            field=models.FileField(null=True, upload_to=importJupyter.models.generate_filename),
        ),
    ]
