# Generated by Django 3.0.3 on 2021-01-16 20:06

from django.db import migrations, models
import django.db.models.deletion
import importJupyter.models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0017_auto_20210115_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookmodel',
            name='notebook_test',
            field=models.FileField(upload_to=importJupyter.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importJupyter.NotebookModel'),
        ),
    ]
