# Generated by Django 3.0.3 on 2021-01-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importJupyter', '0019_documentationposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationposts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
